apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WEBSOCKET_ENABLED
              value: "true"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /alive
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /data
            - name: media-root
              mountPath: /export
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data
        - name: media-root
          persistentVolumeClaim:
            claimName: nfs-tank-root
