apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: nfs://192.168.1.202:/tank/backups/longhorn-backups?nfsOptions=vers=4.2
  credentialSecret: ""
