apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - slurm-home-pv.yaml
  - slurm-home-pvc.yaml
  - slurm-config.yaml
  - slurmctld-service.yaml
  - slurmd-service.yaml
  - slurm-login-service.yaml
  - slurmctld-deployment.yaml
  - slurmd-deployment.yaml
  - slurm-login-deployment.yaml
