apiVersion: v1
kind: Service
metadata:
  name: slurm-login-ssh
  namespace: slurm
spec:
  type: NodePort
  selector:
    app: slurm-login
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022

