apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
  labels:
    recurring-job.longhorn.io/backup-radarr-weekly: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replace-me
  resources:
    requests:
      storage: 4Gi
