---
- name: Set monitoring paths
  ansible.builtin.set_fact:
    monitoring_repo_root: "{{ playbook_dir | dirname }}"
    monitoring_values_file: "{{ (playbook_dir | dirname) + '/k8s/monitoring/kube-prometheus-stack-values.yaml' }}"
    monitoring_rules_file: "{{ (playbook_dir | dirname) + '/k8s/monitoring/prometheus-rules.yaml' }}"

- name: Install kube-prometheus-stack
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_yaml }}"
    name: kube-prometheus-stack
    chart_ref: kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    release_state: present
    chart_version: "{{ monitoring_chart_version }}"
    values: "{{ lookup('ansible.builtin.file', monitoring_values_file) | from_yaml }}"
    wait: true
    wait_timeout: 600s

- name: Apply monitoring custom rules
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_yaml }}"
    state: present
    src: "{{ monitoring_rules_file }}"
