---
- name: Install Traefik Ingress Controller
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_yaml }}"
    name: traefik
    chart_ref: traefik
    release_namespace: traefik
    create_namespace: true
    chart_repo_url: https://traefik.github.io/charts
    release_state: present
    chart_version: "{{ traefik_chart_version }}"
    values:
      ingressClass:
        enabled: true
        isDefaultClass: false
      service:
        type: LoadBalancer
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      providers:
        kubernetesIngress:
          publishedService:
            enabled: true
