apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mealie.fol3y.us
      secretName: mealie-tls
  rules:
    - host: mealie.fol3y.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mealie
                port:
                  number: 80
